package com.example.dealbpm.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DealTeam implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String assignPMs;
	private String assignDMs;
	private String assignApprovers;

	public DealTeam() {
	}

	public java.lang.String getAssignPMs() {
		return this.assignPMs;
	}

	public void setAssignPMs(java.lang.String assignPMs) {
		this.assignPMs = assignPMs;
	}

	public java.lang.String getAssignDMs() {
		return this.assignDMs;
	}

	public void setAssignDMs(java.lang.String assignDMs) {
		this.assignDMs = assignDMs;
	}

	public java.lang.String getAssignApprovers() {
		return this.assignApprovers;
	}

	public void setAssignApprovers(java.lang.String assignApprovers) {
		this.assignApprovers = assignApprovers;
	}

	public DealTeam(java.lang.String assignPMs, java.lang.String assignDMs,
			java.lang.String assignApprovers) {
		this.assignPMs = assignPMs;
		this.assignDMs = assignDMs;
		this.assignApprovers = assignApprovers;
	}
	
	@Override
	public String toString() {
		return "DealTeam [assignPMs=" + assignPMs + ", assignDMs=" + assignDMs
				+ ", assignApprovers=" + assignApprovers + "]";
	}


}